# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  #Linux编译
  Build-Linux:
    #运行平台
    name: Build on Linux
    runs-on: ubuntu-latest
    #编译步骤
    steps:
      #1安装Qt
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '6.2.4'
          host: 'linux'
          arch: 'gcc_64'
          target: 'desktop'
      #2拉取代码
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      #3编译构建
      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make