name: telegram message
on: [ push ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: get yiyan
        run: |
          curl https://v1.hitokoto.cn
          echo "\"YIYAN"="'$(curl international.v1.hitokoto.cn | jq -r .hitokoto)'\""
          echo "\"YIYAN"="'$(curl international.v1.hitokoto.cn | jq -r .hitokoto)'\"" >> $GITHUB_ENV
      - name: use
        run: |
          echo ${{ env.YIYAN }}
