name: telegram message
on: [ push ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # 获取一言
      - name: get yiyan
        run: |
          echo "YIYAN=$(curl 'https://v1.hitokoto.cn?c=a&c=d&c=i&c=j&c=k' | jq -r .hitokoto)" >> $GITHUB_ENV
      # 配置python
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - run: |
          pip install python-telegram-bot # telegram.__version__ = 13.3
      # 拉取代码
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      # 发送消息
      - name: send to telegram
        env:
          TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TO: ${{ secrets.TELEGRAM_TO }}
          actor: ${{ github.actor }}
          message: ${{ github.event.commits[0].message }}
          repository: ${{ github.repository }}
          sha: ${{github.sha}}
          yiyan: ${{ env.YIYAN }}
        run: |
          python scripts/main.py