name: telegram message
on: [ push ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: get yiyan
        run: |
          echo "\"YIYAN"="'$(curl v1.hitokoto.cn | jq -r .hitokoto)'\""
          echo "\"YIYAN"="'$(curl v1.hitokoto.cn | jq -r .hitokoto)'\"" >> $GITHUB_ENV
      - name: use
        run: |
          echo ${{ env.YIYAN }}
